spring:
  datasource:
    url: jdbc:postgresql://${postgres.railway.internal}:${5432}/${railway}
    username: ${postgres}
    password: ${EdcEkxJrIpdSncivqIwELycvGMRsIAbn}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create